# === correctness ===

#absurd_extreme_comparisons
#almost_swapped
#approx_constant
#async_yields_async
#bad_bit_mask
#cast_ref_to_mut
#clone_double_ref
#cmp_nan
#deprecated_semver
#derive_hash_xor_eq
#derive_ord_xor_partial_ord
#drop_copy
#drop_ref
#enum_clike_unportable_variant
#eq_op
#erasing_op
#fn_address_comparisons
#forget_copy
#forget_ref
#if_let_mutex
#if_same_then_else
#ifs_same_cond
#ineffective_bit_mask
#infinite_iter
#inherent_to_string_shadow_display
#inline_fn_without_body
#invalid_null_ptr_usage
#invalid_regex
#invisible_characters
#iter_next_loop
#iterator_step_by_zero
#let_underscore_lock
#logic_bug
#match_str_case_mismatch
#mem_replace_with_uninit
#min_max
#mismatched_target_os
#mistyped_literal_suffixes
#modulo_one
#mut_from_ref
#never_loop
#non_octal_unix_permissions
#nonsensical_open_options
#not_unsafe_ptr_arg_deref
#option_env_unwrap
#out_of_bounds_indexing
#panicking_unwrap
#possible_missing_comma
#reversed_empty_ranges
#self_assignment
#serde_api_misuse
#size_of_in_element_count
#suspicious_splitn
#to_string_in_display
#transmuting_null
#undropped_manually_drops
#uninit_assumed_init
#uninit_vec
#unit_cmp
#unit_hash
#unit_return_expecting_ord
#unsound_collection_transmute
#unused_io_amount
#useless_attribute
#vec_resize_to_zero
#vtable_address_comparisons
#while_immutable_condition
#wrong_transmute
#zst_offset

# == complexity ===

#bind_instead_of_map
#bool_comparison
#borrowed_box
#char_lit_as_u8
#clone_on_copy
#crosspointer_transmute
#deprecated_cfg_attr
#deref_addrof
#derivable_impls
#diverging_sub_expression
#double_comparisons
#double_parens
#duration_subsec
#explicit_counter_loop
#explicit_write
#extra_unused_lifetimes
#filter_map_identity
#filter_next
#flat_map_identity
#get_last_with_len
#identity_op
#inspect_for_each
#int_plus_one
#iter_count
#manual_filter_map
#manual_find_map
#manual_flatten
#manual_split_once
#manual_strip
#manual_swap
#manual_unwrap_or
#map_flatten
#map_identity
#match_as_ref
#match_single_binding
#needless_arbitrary_self_type
#needless_bool
#needless_borrowed_reference
#needless_lifetimes
#needless_option_as_deref
#needless_question_mark
#needless_splitn
#needless_update
#neg_cmp_op_on_partial_ord
#no_effect
#nonminimal_bool
#option_as_ref_deref
#option_filter_map
#option_map_unit_fn
#overflow_check_conditional
#partialeq_ne_impl
#precedence
#ptr_offset_with_cast
#range_zip_with_len
#redundant_closure_call
#redundant_slicing
#ref_in_deref
#repeat_once
#result_map_unit_fn
#search_is_some
#short_circuit_statement
#single_element_loop
#skip_while_next
#string_from_utf8_as_bytes
#strlen_on_c_strings
#temporary_assignment
#too_many_arguments
#transmute_bytes_to_str
#transmute_float_to_int
#transmute_int_to_bool
#transmute_int_to_char
#transmute_int_to_float
#transmute_num_to_bytes
#transmute_ptr_to_ref
#transmutes_expressible_as_ptr_casts
#type_complexity
#unit_arg
#unnecessary_cast
#unnecessary_filter_map
#unnecessary_operation
#unnecessary_sort_by
#unnecessary_unwrap
#unneeded_wildcard_pattern
#useless_asref
#useless_conversion
#useless_format
#vec_box
#while_let_loop
#wildcard_in_or_patterns
#zero_divided_by_zero
#zero_prefixed_literal

# === cargo ===

#cargo_common_metadata
#multiple_crate_versions
#negative_feature_names
#redundant_feature_names
#wildcard_dependencies

# === nursery ===

#branches_sharing_code
#cognitive_complexity
#debug_assert_with_mut_call
#disallowed_methods
#disallowed_types
#empty_line_after_outer_attr 
#equatable_if_let 
#fallible_impl_from 
#future_not_send
#imprecise_flops
#index_refutable_slice 
#missing_const_for_fn
#mutex_integer
#non_send_fields_in_send_ty
#nonstandard_macro_braces
#option_if_let_else 
#path_buf_push_overwrite
#redundant_pub_crate 
#string_lit_as_bytes 
#suboptimal_flops
#suspicious_operation_groupings
#trailing_empty_array
#trivial_regex
#use_self 
#useless_let_if_seq 
#useless_transmute

# === pedantic ===

#await_holding_lock
#await_holding_refcell_ref
#case_sensitive_file_extension_comparisons
#cast_lossless
#cast_possible_truncation
#cast_possible_wrap
#cast_precision_loss
#cast_ptr_alignment
#cast_sign_loss
#checked_conversions
#cloned_instead_of_copied
#copy_iterator
#default_trait_access
#doc_markdown
#empty_enum
#enum_glob_use
#expl_impl_clone_on_copy
#explicit_deref_methods
#explicit_into_iter_loop
#explicit_iter_loop
#filter_map_next
#flat_map_option
#float_cmp
#fn_params_excessive_bools
#from_iter_instead_of_collect
#if_not_else
#implicit_clone
#implicit_hasher
#implicit_saturating_sub
#inconsistent_struct_constructor
#inefficient_to_string
#inline_always
#invalid_upcast_comparisons
#items_after_statements
#iter_not_returning_iterator
#large_digit_groups
#large_stack_arrays
#large_types_passed_by_value
#let_underscore_drop
#let_unit_value
#linkedlist
#macro_use_imports
#manual_assert
#manual_ok_or
#many_single_char_names
#map_unwrap_or
#match_bool
#match_on_vec_items
#match_same_arms
#match_wild_err_arm
#match_wildcard_for_single_variants
#maybe_infinite_iter
#missing_errors_doc
#missing_panics_doc
#module_name_repetitions
#must_use_candidate
#mut_mut
#naive_bytecount
#needless_bitwise_bool
#needless_continue
#needless_for_each
#needless_pass_by_value
#no_effect_underscore_binding
#option_option
#ptr_as_ptr
#range_minus_one
#range_plus_one
#redundant_closure_for_method_calls
#redundant_else
#ref_binding_to_reference
#ref_option_ref
#same_functions_in_if_condition

# === perf ===

#box_collection
#boxed_local
#cmp_owned
#expect_fun_call
#extend_with_drain
#format_in_format_args
#iter_nth
#large_const_arrays
#large_enum_variant
#manual_memcpy
#manual_str_repeat
#map_entry
#mutex_atomic
#needless_collect
#or_fun_call
#redundant_allocation
#redundant_clone
#single_char_pattern
#slow_vector_initialization
#stable_sort_primitive 
#to_string_in_format_args
#unnecessary_to_owned
#useless_vec
#vec_init_then_push

# === restriction ===

#as_conversions
#clone_on_ref_ptr
#create_dir
#dbg_macro
#decimal_literal_representation
#default_numeric_fallback
#disallowed_script_idents
#else_if_without_else 
#exhaustive_enums
#exhaustive_structs
#exit
#expect_used
#filetype_is_file
#float_arithmetic
#float_cmp_const
#fn_to_numeric_cast_any
#get_unwrap
#if_then_some_else_none
#implicit_return
#indexing_slicing
#inline_asm_x86_att_syntax
#inline_asm_x86_intel_syntax
#integer_arithmetic
#integer_division
#let_underscore_must_use
#lossy_float_literal
#map_err_ignore
#mem_forget
#missing_docs_in_private_items
#missing_enforced_import_renames
#missing_inline_in_public_items
#mod_module_files
#modulo_arithmetic
#multiple_inherent_impl
#non_ascii_literal
#panic
#panic_in_result_fn
#pattern_type_mismatch
#print_stderr
#print_stdout
#rc_buffer
#rc_mutex
#rest_pat_in_fully_bound_structs
#same_name_method
#self_named_module_files
#separated_literal_suffix
#shadow_reuse
#shadow_same
#shadow_unrelated
#str_to_string
#string_add
#string_slice
#string_to_string
#todo
#undocumented_unsafe_blocks
#unimplemented
#unnecessary_self_imports
#unneeded_field_pattern
#unreachable
#unseparated_literal_suffix
#unwrap_in_result
#unwrap_used
#use_debug
#verbose_file_reads
#wildcard_enum_match_arm

# === style ===

#assertions_on_constants
#assign_op_pattern
#blacklisted_name
#blocks_in_if_conditions
#bool_assert_comparison
#borrow_interior_mutable_const
#builtin_type_shadow
#bytes_nth
#chars_last_cmp
#chars_next_cmp
#cmp_null
#collapsible_else_if
#collapsible_if
#collapsible_match
#comparison_chain
#comparison_to_empty
#declare_interior_mutable_const
#double_must_use
#double_neg
#duplicate_underscore_argument
#enum_variant_names
#excessive_precision
#field_reassign_with_default
#fn_to_numeric_cast
#fn_to_numeric_cast_with_truncation
#for_kv_map
#from_over_into
#from_str_radix_10
#inconsistent_digit_grouping
#infallible_destructuring_match
#inherent_to_string
#into_iter_on_ref
#iter_cloned_collect
#iter_next_slice
#iter_nth_zero
#iter_skip_next
#just_underscores_and_digits
#len_without_is_empty
#len_zero
#let_and_return
#main_recursion
#manual_async_fn
#manual_map
#manual_non_exhaustive
#manual_range_contains
#manual_saturating_arithmetic
#map_clone
#map_collect_result_unit
#match_like_matches_macro
#match_overlapping_arm
#match_ref_pats
#match_result_ok
#mem_replace_option_with_none
#mem_replace_with_default
#missing_safety_doc
#mixed_case_hex_literals
#module_inception
#must_use_unit
#mut_mutex_lock
#needless_borrow
#needless_doctest_main
#needless_late_init
#needless_range_loop
#needless_return
#neg_multiply
#new_ret_no_self
#new_without_default
#ok_expect
#op_ref
#option_map_or_none
#print_literal
#print_with_newline
#println_empty_string
#ptr_arg
#ptr_eq
#question_mark
#redundant_closure
#redundant_field_names
#redundant_pattern
#redundant_pattern_matching
#redundant_static_lifetimes
#result_map_or_into_option
#result_unit_err
#same_item_push
#self_named_constructors
#should_implement_trait
#single_char_add_str
#single_component_path_imports
#single_match
#string_extend_chars
#tabs_in_doc_comments
#to_digit_is_some
#toplevel_ref_arg
#try_err
#unnecessary_fold
#unnecessary_lazy_evaluations
#unnecessary_mut_passed
#unsafe_removed_from_name
#unused_unit
#unusual_byte_groupings
#unwrap_or_else_default
#upper_case_acronyms
#while_let_on_iterator
#write_literal
#write_with_newline
#writeln_empty_string
#wrong_self_convention
#zero_ptr

# === suspicious ===

#blanket_clippy_restriction_lints
#empty_loop
#eval_order_dependence
#float_equality_without_abs
#for_loops_over_fallibles
#misrefactored_assign_op
#mut_range_bound
#mutable_key_type
#octal_escapes
#return_self_not_must_use
#suspicious_arithmetic_impl
#suspicious_assignment_formatting ¶
#suspicious_else_formatting
#suspicious_map
#suspicious_op_assign_impl
#suspicious_unary_op_formatting
