[package]
name = "aurora-engine-tests"
version = "1.0.0"
authors = ["NEAR <hello@near.org>"]
edition = "2018"
description = ""
documentation = ""
readme = true
homepage = "https://github.com/aurora-is-near/aurora-engine"
repository = "https://github.com/aurora-is-near/aurora-engine"
license = "GPL-3.0"
publish = false
autobenches = false

[dependencies]
aurora-engine = { path = "../engine", default-features = false, features = ["sha2"] }
aurora-engine-types = { path = "../engine-types", default-features = false }
aurora-engine-sdk = { path = "../engine-sdk", default-features = false }
aurora-engine-precompiles = { path = "../engine-precompiles", default-features = false }
borsh = { version = "0.8.2", default-features = false }
byte-slice-cast = { version = "1.0", default-features = false }
sha3 = { version = "0.9.1", default-features = false }
evm = { git = "https://github.com/aurora-is-near/sputnikvm.git", default-features = false }
rlp = { version = "0.5.0", default-features = false }

[dev-dependencies]
aurora-engine-precompiles = { path = "../engine-precompiles" }
bstr = "0.2"
ethabi = { git = "https://github.com/darwinia-network/ethabi", branch = "xavier-no-std" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = { version = "0.4.3", default-features = false }
near-sdk = { git = "https://github.com/aurora-is-near/near-sdk-rs.git", rev = "5e58722bd61d9d24ae6293326146c751f0a814fb" }
near-sdk-sim = { git = "https://github.com/aurora-is-near/near-sdk-rs.git", rev = "5e58722bd61d9d24ae6293326146c751f0a814fb" }
near-crypto = { git = "https://github.com/near/nearcore.git", rev = "0c9ad79a18e431f843e6123cf4559f9c2c5dd228" }
near-vm-runner = { git = "https://github.com/near/nearcore.git", rev = "0c9ad79a18e431f843e6123cf4559f9c2c5dd228" }
near-vm-logic = { git = "https://github.com/near/nearcore.git", rev = "0c9ad79a18e431f843e6123cf4559f9c2c5dd228" }
near-primitives-core = { git = "https://github.com/near/nearcore.git", rev = "0c9ad79a18e431f843e6123cf4559f9c2c5dd228" }
near-primitives = { git = "https://github.com/near/nearcore.git", rev = "0c9ad79a18e431f843e6123cf4559f9c2c5dd228" }
wasmer = { package = "wasmer-near", version = "2.0.1", default-features = false, features = ["singlepass", "universal"] }
libsecp256k1 = "0.3.5"
rand = "0.7.3"
criterion = "0.3.4"
git2 = "0.13"
parity-bytes = "0.1"
ethereum-types = "0.12"
rustc-hex = "2.1.0"
maplit = "1.0.2"
arrayref = "0.3.5"
tiny-keccak = "2.0.2"
hash-db = "0.15.2"
plain_hasher = "0.2"
triehash = "0.8.4"
base64ct = "<1.2.0"
parity-crypto = { version = "0.9", features = ["publickey"] }
lazy_static = "1.4.0"
substrate-bn = { git = "https://github.com/paritytech/bn", default-features = false }
byteorder = "1.3.2"
keccak-hash = "0.7"
log = "0.4"
num = "0.2"
eth_pairings = { git = "https://github.com/matter-labs/eip1962.git", default-features = false, features = ["eip_2537"], rev = "ece6cbabc41948db4200e41f0bfdab7ab94c7af8" }
hex-literal = "0.2.1"

[features]
meta-call = ["aurora-engine/meta-call"]
mainnet-test = ["aurora-engine/mainnet-test", "test-helpers"]
testnet-test = ["aurora-engine/testnet-test", "test-helpers"]
betanet-test = ["aurora-engine/betanet-test", "test-helpers"]
error_refund = ["aurora-engine/error_refund", "aurora-engine-precompiles/error_refund"]
test-helpers = []
